version: "3"  
services: 
  jenkins:  
    container_name: dev-jenkins
    image: jenkins/jenkins:lts 
    restart: always
    privileged: true
    volumes:  
      - /var/jenkins_home/:/var/jenkins_home
      - /usr/local/jdk1.8.0_45/:/usr/local/jdk
      - /usr/local/sonar-scanner-3.1.0.1141:/usr/local/sonar-scanner-3.1.0.1141     
      - /usr/local/apache-maven-3.5.0:/usr/local/apache-maven-3.5.0
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      -  ~/.ssh:/root/.ssh
    environment:
      TZ: ${GLOBAL_TIME_ZONE}
      JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
    ports:
      - "80:8080"
  